In [ ]:
from google.colab import drive

drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
!pip install mikeio==1.4.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.2/147.2 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 10.7 MB/s eta 0:00:00


In [ ]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import mikeio
from mikeio import ItemInfo, EUMType, EUMUnit
from datetime import datetime

In [ ]:
parent = "drive/MyDrive/Workstation/mikeAuto/"
paths = [parent+i for i in os.listdir(parent) if i[0]=="3"]
paths

['drive/MyDrive/Workstation/mikeAuto/3-Hourly Rainfall.xlsx',
 'drive/MyDrive/Workstation/mikeAuto/3-Hourly Wind Sp. & Dir..xlsx']

In [ ]:
if not os.path.exists(parent+"mikeAuto/"):
  os.mkdir(parent+"mikeAuto/")

output = parent+"mikeAuto/"

In [ ]:
wind = pd.read_excel(paths[1])
rain = pd.read_excel(paths[0])

wind.tail()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
488      12103       2022         12          9          2         27   
489      12103       2022         12         12          0          0   
490      12103       2022         12         15          0          0   
491      12103       2022         12         18          0          0   
492      12103       2022         12         21          0          0   

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ... Unnamed: 56 Unnamed: 57  \
488          4         36          4         31  ...           3          26   
489          0          0          0          0  ...           0           0   
490          0          0          0          0  ...           0           0   
491          0          0          0          0  ...           0           0   
492          0          0          0          0  ...           0           0   

    Unnamed: 58 Unnamed: 59 Unnamed: 60 Unnamed: 61 Unnamed: 62 Unnamed: 63  \
488           1          36           4          31           4          27   
489           0           0           0           0           0           0   
490           0           0           0           0           0           0   
491           2          33           0           0           0           0   
492           6          36           0           0           0           0   

    Unnamed: 64 Unnamed: 65  
488           2          36  
489           0           0  
490           0           0  
491           0           0  
492           0           0  

[5 rows x 66 columns]

In [ ]:
n1 = [1,2,3,4,5]

n2 = [6,7,8,9,10]

np.concatenate([n1, n2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
[[[3,4,5] for j in range(4)] for i in range(5)]

[[[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5]],
 [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5]],
 [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5]],
 [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5]],
 [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5]]]

In [ ]:
data = wind.copy()
year = 2022
month = 4
wn1 = data[data["Unnamed: 1"]==year]
wn2 = wn1[wn1["Unnamed: 2"]==month]

wn3 = wn2.drop(["Unnamed: 0", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3"], axis = 1)

#np.concatenate([wn3[i] for i in wn3.columns if (int(i[-1]))%2 == 0])[40:216]

wind_speed = np.concatenate([wn3[i] for i in wn3.columns if (int(i[-1]))%2==0])[40:216]

#augmented_data = np.ravel([[data[i] for j in range(deltaNumber)] for i in range(len(data))])

np.ravel([[wind_speed[i] for j in range(36)] for i in range(len(wind_speed))])

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
["custom" for i in range(5)]

['custom', 'custom', 'custom', 'custom', 'custom']

In [ ]:
#pd.to_datetime(list(np.concatenate([list(np.concatenate([[datetime(2022, month,j, i,k, 0) for k in range(0,60,timeDelta)] for i in range(24)])) for j in range(startDate,endDate+1,1)])))



pd.to_datetime(list(np.concatenate(np.concatenate([[[datetime(2022, 4,j, i,k, 0) for k in range(0,60,5)] for i in range(24)] for j in range(5,26+1,1)]))))


DatetimeIndex(['2022-04-05 00:00:00', '2022-04-05 00:05:00',
               '2022-04-05 00:10:00', '2022-04-05 00:15:00',
               '2022-04-05 00:20:00', '2022-04-05 00:25:00',
               '2022-04-05 00:30:00', '2022-04-05 00:35:00',
               '2022-04-05 00:40:00', '2022-04-05 00:45:00',
               ...
               '2022-04-26 23:10:00', '2022-04-26 23:15:00',
               '2022-04-26 23:20:00', '2022-04-26 23:25:00',
               '2022-04-26 23:30:00', '2022-04-26 23:35:00',
               '2022-04-26 23:40:00', '2022-04-26 23:45:00',
               '2022-04-26 23:50:00', '2022-04-26 23:55:00'],
              dtype='datetime64[ns]', length=6336, freq=None)

In [ ]:
def select_year_and_month(year, month, data):
  wn1 = data[data["Unnamed: 1"]==year]
  wn2 = wn1[wn1["Unnamed: 2"]==month]

  wn3 = wn2.drop(["Unnamed: 0", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3"], axis = 1)

  return wn3


def inject_data(data, deltaNumber):
  augmented_data = np.ravel([[data[i] for j in range(deltaNumber)] for i in range(len(data))])

  return augmented_data


def datetimeFix(month, startDate, endDate, timeDelta):
  return pd.to_datetime(list(np.concatenate([list(np.concatenate([[datetime(2022, month,j, i,k, 0) for k in range(0,60,timeDelta)] for i in range(24)])) for j in range(startDate,endDate+1,1)])))



In [ ]:
#print("Enter Year:\n")
#year = int(input())
#print("\nEnter Month:\n")
#month = int(input())
year = 2022
month = 4

wn3 = select_year_and_month(year, month, wind)

wind_speed = np.concatenate([wn3[i] for i in wn3.columns if (int(i[-1]))%2 == 0])[40:216]

wind_direction = np.concatenate([wn3[i] for i in wn3.columns if (int(i[-1]))%2 != 0])[40:216]


augmented_windSpeed = inject_data(wind_speed,36)  # 36 data in 3 hours with 5 minutes time interval

augmented_windSpeed_direction = inject_data(wind_direction,36)


time = datetimeFix(4, 5, 26, 5)   # 05/04/22 to 26/04/22 with 5 miutes time interval

da1 = mikeio.DataArray(data = augmented_windSpeed[96:],time = time[96:], item = EUMType.Wind_speed) # Dataset from 8 am

da2 = mikeio.DataArray(data = augmented_windSpeed_direction[96:],time = time[96:], item = EUMType.Wind_Direction)

ds = mikeio.Dataset([da1, da2])
ds.to_dfs(output+"wind_forcing_{y}_{m}.dfs0".format(y = year, m = month))

windio = mikeio.read(output+"wind_forcing_{y}_{m}.dfs0".format(y = year, m = month))

windio

<mikeio.Dataset>
dims: (time:6240)
time: 2022-04-05 08:00:00 - 2022-04-26 23:55:00 (6240 records)
geometry: GeometryUndefined()
items:
  0:  Wind speed <Wind speed> (meter per sec)
  1:  Wind Direction <Wind Direction> (degree)

In [ ]:
windio.Wind_speed.values

array([4., 4., 4., ..., 0., 0., 0.])

In [ ]:
"wind_forcing_{y}_{m}.dfs0".format(y = 2022, m = 4)

'wind_forcing_2022_4.dfs0'

In [ ]:
EUMType.Wind_speed

Wind speed

In [ ]:
rain.tail()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4  Unnamed: 5  \
487      12103       2022         12          9         0.0         0.0   
488      12103       2022         12         12         0.0         0.0   
489      12103       2022         12         15         0.0         0.0   
490      12103       2022         12         18         0.0         0.0   
491      12103       2022         12         21         0.0         0.0   

     Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unnamed: 25  \
487         0.0         0.0         0.0         0.0  ...          0.0   
488         0.0         0.0         0.0         0.0  ...          0.0   
489         0.0         0.0         0.0         0.0  ...          0.0   
490         0.0         0.0         0.0         0.0  ...          0.0   
491         0.0         0.0         0.0         0.0  ...          0.0   

     Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30  \
487          0.0          0.0          0.0          0.0          0.0   
488          0.0          0.0          0.0          0.0          0.0   
489          0.0          0.0          0.0          0.0          0.0   
490          0.0          0.0          0.0          0.0          0.0   
491          0.0          0.0          0.0          0.0          0.0   

     Unnamed: 31  Unnamed: 32  Unnamed: 33  Unnamed: 34  
487          0.0          0.0          0.0          0.0  
488          0.0          0.0          0.0          0.0  
489          0.0          0.0          0.0          0.0  
490          0.0          0.0          0.0          0.0  
491          0.0          0.0          0.0          0.0  

[5 rows x 35 columns]

In [ ]:
#print("Enter Year:\n")
#year = int(input())
#print("\nEnter Month:\n")
#month = int(input())
year = 2022
month = 4


wn3 = select_year_and_month(year, month, rain)

precipitation = np.concatenate([wn3[i] for i in wn3.columns])[40:216]

augmented_precipitation = inject_data(precipitation,36)  # 36 data in 3 hours with 5 minutes time interval

time = datetimeFix(4, 5, 26, 5)   # 05/04/22 to 26/04/22 with 5 miutes time interval

da1 = mikeio.DataArray(data = augmented_precipitation[:96],time = time[:96], item = EUMType.Precipitation_Rate)



ds = mikeio.Dataset([da1])
ds.to_dfs(output+"precipitation_{y}_{m}.dfs0".format(y = year, m = month))

pcio = mikeio.read(output+"precipitation_{y}_{m}.dfs0".format(y = year, m = month))

pcio

<mikeio.Dataset>
dims: (time:96)
time: 2022-04-05 00:00:00 - 2022-04-05 07:55:00 (96 records)
geometry: GeometryUndefined()
items:
  0:  Precipitation Rate <Precipitation Rate> (mm per day)

In [ ]:
EUMType.Precipitation_Rate, time

(Precipitation Rate,
 DatetimeIndex(['2022-04-05 00:00:00', '2022-04-05 00:05:00',
                '2022-04-05 00:10:00', '2022-04-05 00:15:00',
                '2022-04-05 00:20:00', '2022-04-05 00:25:00',
                '2022-04-05 00:30:00', '2022-04-05 00:35:00',
                '2022-04-05 00:40:00', '2022-04-05 00:45:00',
                ...
                '2022-04-26 23:10:00', '2022-04-26 23:15:00',
                '2022-04-26 23:20:00', '2022-04-26 23:25:00',
                '2022-04-26 23:30:00', '2022-04-26 23:35:00',
                '2022-04-26 23:40:00', '2022-04-26 23:45:00',
                '2022-04-26 23:50:00', '2022-04-26 23:55:00'],
               dtype='datetime64[ns]', length=6336, freq=None))

#Salinity and temperature

In [ ]:
path = [parent+i for i in os.listdir(parent) if i[:3]=="Kor"][0]
path

'drive/MyDrive/Workstation/mikeAuto/Kor050422_092401.xlsx'

In [ ]:
data = pd.read_excel(path)
data["date"] = data['Date (MM/DD/YYYY)']
data["time"] = data['Time (HH:mm:ss)']
data['temp'] = data['Temp °C']
data['salinity'] = data['Sal psu']

temp_ = data.drop([i for i in data.columns if i not in ["date", "time", "temp"]], axis = 1)

temp = temp_[temp_['date']<'2022-04-27']


salt_ = data.drop([i for i in data.columns if i not in ["date", "time", "salinity"]], axis = 1)

salt = salt_[salt_['date']<'2022-04-27']

salt

date      time  salinity
0    2022-04-05  08:00:00      0.79
1    2022-04-05  08:30:00      0.73
2    2022-04-05  09:00:00      1.28
3    2022-04-05  09:30:00      0.59
4    2022-04-05  10:00:00      3.20
...         ...       ...       ...
1035 2022-04-26  21:30:00      2.36
1036 2022-04-26  22:00:00      2.57
1037 2022-04-26  22:30:00      2.60
1038 2022-04-26  23:00:00      2.83
1039 2022-04-26  23:30:00      2.85

[1040 rows x 3 columns]

In [ ]:
len(temp.temp.values)*6

6240

In [ ]:
data['date']

0      2022-04-05
1      2022-04-05
2      2022-04-05
3      2022-04-05
4      2022-04-05
          ...    
1388   2022-05-04
1389   2022-05-04
1390   2022-05-04
1391   2022-05-04
1392   2022-05-04
Name: date, Length: 1393, dtype: datetime64[ns]

In [ ]:
temperature = temp.temp.values

augmented_temperature = inject_data(temperature,6)

year = 2022
month = 4

time = datetimeFix(4, 5, 26, 5)[96:]

da = mikeio.DataArray(data = augmented_temperature,time = time, item = EUMType.Temperature)

ds = mikeio.Dataset([da])
ds.to_dfs(output+"temperature_{y}_{m}.dfs0".format(y = year, m = month))

tempio = mikeio.read(output+"temperature_{y}_{m}.dfs0".format(y = year, m = month))

tempio

<mikeio.Dataset>
dims: (time:6240)
time: 2022-04-05 08:00:00 - 2022-04-26 23:55:00 (6240 records)
geometry: GeometryUndefined()
items:
  0:  Temperature <Temperature> (degree Celsius)

In [ ]:
salinity = salt.salinity.values

augmented_salinity = inject_data(salinity,6)

year = 2022
month = 4

time = datetimeFix(4, 5, 26, 5)[96:]

da = mikeio.DataArray(data = augmented_salinity,time = time, item = EUMType.Salinity)



ds = mikeio.Dataset([da])
ds.to_dfs(output+"salinity_{y}_{m}.dfs0".format(y = year, m = month))

saltio = mikeio.read(output+"salinity_{y}_{m}.dfs0".format(y = year, m = month))

saltio

<mikeio.Dataset>
dims: (time:6240)
time: 2022-04-05 08:00:00 - 2022-04-26 23:55:00 (6240 records)
geometry: GeometryUndefined()
items:
  0:  Salinity <Salinity> (PSU)

In [ ]:
time1 = pd.to_datetime(list(np.concatenate([list(np.concatenate([[datetime(2022, 4,j, i,k, 0) for k in [0,30]] for i in range(24)])) for j in range(1,31,1)])))[16:]


time2 = pd.to_datetime([str(temp.date.values[i])+" "+str(temp.time.values[i]) for i in range(len(temp.date.values))])


[str(i) for i in time1 if str(i) not in [str(j) for j in time2]]


['2022-04-01 08:00:00',
 '2022-04-01 08:30:00',
 '2022-04-01 09:00:00',
 '2022-04-01 09:30:00',
 '2022-04-01 10:00:00',
 '2022-04-01 10:30:00',
 '2022-04-01 11:00:00',
 '2022-04-01 11:30:00',
 '2022-04-01 12:00:00',
 '2022-04-01 12:30:00',
 '2022-04-01 13:00:00',
 '2022-04-01 13:30:00',
 '2022-04-01 14:00:00',
 '2022-04-01 14:30:00',
 '2022-04-01 15:00:00',
 '2022-04-01 15:30:00',
 '2022-04-01 16:00:00',
 '2022-04-01 16:30:00',
 '2022-04-01 17:00:00',
 '2022-04-01 17:30:00',
 '2022-04-01 18:00:00',
 '2022-04-01 18:30:00',
 '2022-04-01 19:00:00',
 '2022-04-01 19:30:00',
 '2022-04-01 20:00:00',
 '2022-04-01 20:30:00',
 '2022-04-01 21:00:00',
 '2022-04-01 21:30:00',
 '2022-04-01 22:00:00',
 '2022-04-01 22:30:00',
 '2022-04-01 23:00:00',
 '2022-04-01 23:30:00',
 '2022-04-02 00:00:00',
 '2022-04-02 00:30:00',
 '2022-04-02 01:00:00',
 '2022-04-02 01:30:00',
 '2022-04-02 02:00:00',
 '2022-04-02 02:30:00',
 '2022-04-02 03:00:00',
 '2022-04-02 03:30:00',
 '2022-04-02 04:00:00',
 '2022-04-02 04:

In [ ]:
time2

DatetimeIndex(['2022-04-05 08:00:00', '2022-04-05 08:30:00',
               '2022-04-05 09:00:00', '2022-04-05 09:30:00',
               '2022-04-05 10:00:00', '2022-04-05 10:30:00',
               '2022-04-05 11:00:00', '2022-04-05 11:30:00',
               '2022-04-05 12:00:00', '2022-04-05 12:30:00',
               ...
               '2022-04-26 19:00:00', '2022-04-26 19:30:00',
               '2022-04-26 20:00:00', '2022-04-26 20:30:00',
               '2022-04-26 21:00:00', '2022-04-26 21:30:00',
               '2022-04-26 22:00:00', '2022-04-26 22:30:00',
               '2022-04-26 23:00:00', '2022-04-26 23:30:00'],
              dtype='datetime64[ns]', length=1040, freq=None)